# Generated by Django 4.0.4 on 2022-04-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productdata_image_cartdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdata',
            name='product',
        ),
        migrations.AddField(
            model_name='orderdata',
            name='product',
            field=models.ManyToManyField(to='product.productdata'),
        ),
    ]
